apiVersion: v1
kind: Service
metadata:
  name: ict-service
  labels:
    name: ict-service
    app: ict-website-app
spec:
  type: NodePort
  ports:
    - port: 3701
      targetPort: 3701
      nodePort: 30009
  selector:
    name: ict-app-pod
    app: ict-website-app
