apiVersion: v1
kind: Pod
metadata:
  name: ict-app-pod
  labels:
    name: ict-app-pod
    app: ict-website-app
spec:
  containers:
    - name: ict-app
      image: adnanm1250/ict-cell
      ports:
        - containerPort: 3701
